This is the notebook where, I'm practicing the basics of pandas.

In [29]:
import pandas as pd

In [5]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"])
df

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [6]:
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [7]:
df.head()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

df.head() provides the first five rows of the dataframe, similarly, df.tail() provides the last five rows of the dataframe.

In [8]:
df.tail()

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

In [9]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [13]:
df['A']

0    1
1    4
2    7
Name: A, dtype: int64

In [14]:
print(df['B'])

0    2
1    5
2    8
Name: B, dtype: int64

In [15]:
print(df['C'])

0    3
1    6
2    9
Name: C, dtype: int64

In [16]:
print(df.index)

RangeIndex(start=0, stop=3, step=1)

In [17]:
print(df.index.to_list())

[0, 1, 2]

This df.index provides the index values as a range type with step value, if we use to_list here, then they will directly convert the range index to a list..

In [18]:
df = pd.DataFrame([[1, 2, 3], [4, 5, 6], [7, 8, 9]], columns=["A", "B", "C"], index=['x', 'y', 'z'])
df

   A  B  C
x  1  2  3
y  4  5  6
z  7  8  9

In [19]:
df.index

Index(['x', 'y', 'z'], dtype='object')

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 3 entries, x to z
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       3 non-null      int64
 1   B       3 non-null      int64
 2   C       3 non-null      int64
dtypes: int64(3)
memory usage: 96.0+ bytes

In [22]:
df.describe()

         A    B    C
count  3.0  3.0  3.0
mean   4.0  5.0  6.0
std    3.0  3.0  3.0
min    1.0  2.0  3.0
25%    2.5  3.5  4.5
50%    4.0  5.0  6.0
75%    5.5  6.5  7.5
max    7.0  8.0  9.0

The df.describe helps to get some info about the dataframe.

In [24]:
df.nunique()

A    3
B    3
C    3
dtype: int64

The df.nunique helps to get the number of unique values in a column.

In [25]:
df.unique()

AttributeError: 'DataFrame' object has no attribute 'unique'

In [26]:
df['A'].unique()

array([1, 4, 7])

In [27]:
type(df['A'].unique())

numpy.ndarray

In [28]:
df.size

9

It returns the total number of elements in the dataframe.

In [30]:
coffee = pd.read_csv("coffee.csv")
coffee

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [31]:
coffee.head()

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
3    Tuesday       Latte          20
4  Wednesday    Espresso          35

In [32]:
coffee.tail()

         Day Coffee Type  Units Sold
9     Friday       Latte          35
10  Saturday    Espresso          45
11  Saturday       Latte          35
12    Sunday    Espresso          45
13    Sunday       Latte          35

We can also provide the URL of raw type of the dataset which is present online. Using the same read_csv function, we can extract that dataset by providing that URL as input.

In [33]:
temp = pd.read_parquet(r"https://github.com/KeithGalli/complete-pandas-tutorial/blob/master/data/results.parquet")
temp

ArrowInvalid: Could not open Parquet input source '<Buffer>': Parquet magic bytes not found in footer. Either the file is corrupted or this is not a parquet file.

Here, we should not provide this type of github link as input. Also, When I tried to get the Raw URL by clicking "Raw" in github, the file is automatically downloaded..

In [34]:
display(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

In [35]:
print(coffee)

          Day Coffee Type  Units Sold
0      Monday    Espresso          25
1      Monday       Latte          15
2     Tuesday    Espresso          30
3     Tuesday       Latte          20
4   Wednesday    Espresso          35
5   Wednesday       Latte          25
6    Thursday    Espresso          40
7    Thursday       Latte          30
8      Friday    Espresso          45
9      Friday       Latte          35
10   Saturday    Espresso          45
11   Saturday       Latte          35
12     Sunday    Espresso          45
13     Sunday       Latte          35

This is a function from IPython.display which is used to display the content of a file in a neat, elegant format. When print is used, it will print the data in a direct text format, with which, there may be misalignments in the Columnar data..

In [52]:
coffee.sample(5, replace = False, random_state = 23)

         Day Coffee Type  Units Sold
0     Monday    Espresso          25
1     Monday       Latte          15
2    Tuesday    Espresso          30
10  Saturday    Espresso          45
13    Sunday       Latte          35

df.sample helps to get some sample data from the dataset, by default, the number of rows returned is 1, we can pass number of rows to return. Also, there is a parameter called replace, which will say whether a row can be repeated in the returned results or not. random_state parameter helps in making the random rows such that, whenever that random state value is provided, that set of rows are returned..

In [55]:
coffee.loc[3]

Day            Tuesday
Coffee Type      Latte
Units Sold          20
Name: 3, dtype: object

In [56]:
coffee.loc[[1, 4, 5]]

         Day Coffee Type  Units Sold
1     Monday       Latte          15
4  Wednesday    Espresso          35
5  Wednesday       Latte          25

In [57]:
coffee.loc[4:8]

         Day Coffee Type  Units Sold
4  Wednesday    Espresso          35
5  Wednesday       Latte          25
6   Thursday    Espresso          40
7   Thursday       Latte          30
8     Friday    Espresso          45

df.loc[] is a property, which, can be used to access, select and modify data in a dataframe using label-based indexing. Syntax: df.loc[row_indexer, column_indexer]. Above formats can also be used..

In [59]:
coffee.loc[5:8, ["Day", "Units Sold"]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30
8     Friday          45

In [60]:
coffee.loc[:, ["Day", "Units Sold"]]

          Day  Units Sold
0      Monday          25
1      Monday          15
2     Tuesday          30
3     Tuesday          20
4   Wednesday          35
5   Wednesday          25
6    Thursday          40
7    Thursday          30
8      Friday          45
9      Friday          35
10   Saturday          45
11   Saturday          35
12     Sunday          45
13     Sunday          35

In loc, upper index is inclusive, which is not the case in iloc. In iloc, instead of the column names, we treat them as 0 based index, then, provide the index values as columns.

In [62]:
coffee.iloc[5:8, [0, 2]]

         Day  Units Sold
5  Wednesday          25
6   Thursday          40
7   Thursday          30